services:
  m1:
    build:
      context: .
      dockerfile: ./apps/m1/Dockerfile
    command: npm run dev m1
    depends_on:
      - m2
      - rabbitmq
    ports:
      - '3000:3000'
    # networks:
    #   - app-network
  m2:
    build:
      dockerfile: ./apps/m2/Dockerfile
    command: npm run dev m2
    depends_on:
      - rabbitmq
    # networks:
    #   - app-network
  rabbitmq:
    container_name: primary_db
    image: rabbitmq
    ports:
      - '5672:5672'
  jenkins:
    image: jenkins/jenkins:jdk17
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      # - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  # volumes:
  #   jenkins_home:
# networks:
#   app-network:
#     driver: bridge
