services:
  m1:
    build:
      context: .
      dockerfile: ./apps/m1/Dockerfile
    command: npm run dev m1
    profiles: [main]
    depends_on:
      - m2
      - rabbitmq
    ports:
      - '3000:3000'
    # networks:
    #   - app-network
  m2:
    build:
      dockerfile: ./apps/m2/Dockerfile
    command: npm run dev m2
    profiles: [main]
    depends_on:
      - rabbitmq
    # networks:
    #   - app-network
  rabbitmq:
    image: rabbitmq
    profiles: [main]
    ports:
      - '5672:5672'
  jenkins:
    build:
      context: .
      dockerfile: ./Dockerfile
    profiles: [jenkins]
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - type: volume
        source: test
        target: /var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
    # volumes:
    # - jenkins_home:/var/jenkins_home
    # - C:/Neo/Work/Metapolis/Random/TestMicroservices/microservices:/workspace
volumes:
  test:
# networks:
#   app-network:
#     driver: bridge
